require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CgusController do

  # This should return the minimal set of attributes required to create a valid
  # Cgu. As you add validations to Cgu, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "article" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CgusController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cgus as @cgus" do
      cgu = Cgu.create! valid_attributes
      get :index, {}, valid_session
      assigns(:cgus).should eq([cgu])
    end
  end

  describe "GET show" do
    it "assigns the requested cgu as @cgu" do
      cgu = Cgu.create! valid_attributes
      get :show, {:id => cgu.to_param}, valid_session
      assigns(:cgu).should eq(cgu)
    end
  end

  describe "GET new" do
    it "assigns a new cgu as @cgu" do
      get :new, {}, valid_session
      assigns(:cgu).should be_a_new(Cgu)
    end
  end

  describe "GET edit" do
    it "assigns the requested cgu as @cgu" do
      cgu = Cgu.create! valid_attributes
      get :edit, {:id => cgu.to_param}, valid_session
      assigns(:cgu).should eq(cgu)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cgu" do
        expect {
          post :create, {:cgu => valid_attributes}, valid_session
        }.to change(Cgu, :count).by(1)
      end

      it "assigns a newly created cgu as @cgu" do
        post :create, {:cgu => valid_attributes}, valid_session
        assigns(:cgu).should be_a(Cgu)
        assigns(:cgu).should be_persisted
      end

      it "redirects to the created cgu" do
        post :create, {:cgu => valid_attributes}, valid_session
        response.should redirect_to(Cgu.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cgu as @cgu" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cgu.any_instance.stub(:save).and_return(false)
        post :create, {:cgu => { "article" => "invalid value" }}, valid_session
        assigns(:cgu).should be_a_new(Cgu)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cgu.any_instance.stub(:save).and_return(false)
        post :create, {:cgu => { "article" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cgu" do
        cgu = Cgu.create! valid_attributes
        # Assuming there are no other cgus in the database, this
        # specifies that the Cgu created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cgu.any_instance.should_receive(:update_attributes).with({ "article" => "MyString" })
        put :update, {:id => cgu.to_param, :cgu => { "article" => "MyString" }}, valid_session
      end

      it "assigns the requested cgu as @cgu" do
        cgu = Cgu.create! valid_attributes
        put :update, {:id => cgu.to_param, :cgu => valid_attributes}, valid_session
        assigns(:cgu).should eq(cgu)
      end

      it "redirects to the cgu" do
        cgu = Cgu.create! valid_attributes
        put :update, {:id => cgu.to_param, :cgu => valid_attributes}, valid_session
        response.should redirect_to(cgu)
      end
    end

    describe "with invalid params" do
      it "assigns the cgu as @cgu" do
        cgu = Cgu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cgu.any_instance.stub(:save).and_return(false)
        put :update, {:id => cgu.to_param, :cgu => { "article" => "invalid value" }}, valid_session
        assigns(:cgu).should eq(cgu)
      end

      it "re-renders the 'edit' template" do
        cgu = Cgu.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cgu.any_instance.stub(:save).and_return(false)
        put :update, {:id => cgu.to_param, :cgu => { "article" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cgu" do
      cgu = Cgu.create! valid_attributes
      expect {
        delete :destroy, {:id => cgu.to_param}, valid_session
      }.to change(Cgu, :count).by(-1)
    end

    it "redirects to the cgus list" do
      cgu = Cgu.create! valid_attributes
      delete :destroy, {:id => cgu.to_param}, valid_session
      response.should redirect_to(cgus_url)
    end
  end

end
